src/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>testDecimal__c</fullName>
        <defaultValue>0</defaultValue>
        <label>testDecimal</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/testpageController.cls
public with sharing class testpageController {

    public Applicant__c relatedTo { get; set; }
    public testpageController ()
    {
        Applicant__c app1 = [select testDecimal__c from Applicant__c where id=:'a0390000001aUmC'];
        relatedTo = app1;
        List<CollaborationGroupFeed > colgrp = [SELECT Id, Type, Body, CreatedBy.Name FROM CollaborationGroupFeed where parentId = '0F9900000004Qul' ORDER BY createdDate DESC, Id DESC LIMIT 20];
        System.debug('------------------------------------------------'+colgrp);
    }
}