src/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Interview_Time__c</fullName>
        <label>Interview Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Manager_Email__c</fullName>
        <label>Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Listed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Over due</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestSheduleOverdue.cls
@isTest
private class TestSheduleOverdue 
{
/*
    static testMethod void myUnitTest() 
    {
        // TO DO: implement unit test
        Test.startTest();
        datetime myDate = datetime.newInstance(2011, 10, 19, 12, 30, 2);
        
        Applicant__c applicant=new Applicant__c(Name__c='testname',Manager_Email__c='rangambr@gmail.com',Status__c='Scheduled',Interview_Time__c=myDate);
        
        List<Applicant__c> apps=new List<Applicant__c>();
        apps.add(applicant);
        
        insert apps;
        
        SheduleOverdueChecker shc=new SheduleOverdueChecker();
        String schedule='0 0 23 * * ?';
        System.schedule('Test Shedule',schedule, shc);
        //System.assertEquals('Over due', apps[0].status__c);
        Test.stopTest();
    }*/
}