src/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Manager_Email__c</fullName>
        <label>Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Listed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Over due</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestNotifyManager.cls
@isTest
private class TestNotifyManager {

    static testMethod void myUnitTest() 
    {
        Applicant__c applicant=new Applicant__c(Name__c='testname',Manager_Email__c='rangambr@gmail.com',Status__c='Scheduled');
        try
        {
        	insert applicant;	
        }
        catch(Exception e)
        {
   			System.debug(e);
        }
        applicant.Status__c='Over due';
        try
        {
        	update applicant;
        }
        
        catch(Exception e)
        {
        	System.debug(e);
        }
    }
}