src/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Email_address__c</fullName>
        <label>Email address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Interview_Time__c</fullName>
        <label>Interview Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Listed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Over due</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ApplicantWrapperTest.cls
@isTest
private class ApplicantWrapperTest {

    static testMethod void myUnitTest() {
    	
        viewApplicants viewapplicants_test=new viewApplicants();
        List<Applicant__c> applicants_test=new List <Applicant__c>();
        List<ApplicantWrapper> applicantwraps_test=new List <ApplicantWrapper>();
        
        datetime myDate = datetime.newInstance(2011, 12, 1, 12,30, 2);
        
        //create applicants - add to a list
        Applicant__c app1=new Applicant__c(Name__c='applicant1',Email_address__c='abc@xxx.com',Interview_Time__c=myDate,Status__c='New');
        applicants_test.add(app1);
        
        Applicant__c app2=new Applicant__c(Name__c='applicant2',Email_address__c='abc@xxx.com',Interview_Time__c=myDate,Status__c='Scheduled');
        applicants_test.add(app2);
        
        Applicant__c app3=new Applicant__c(Name__c='applicant3',Email_address__c='abc@xxx.com',Interview_Time__c=myDate,Status__c='Short Listed');
        applicants_test.add(app3);
        
        Applicant__c app4=new Applicant__c(Name__c='applicant4',Email_address__c='abc@xxx.com',Interview_Time__c=myDate,Status__c='Selected');
        applicants_test.add(app4);
        
        Applicant__c app5=new Applicant__c(Name__c='applicant5',Interview_Time__c=myDate,Status__c='Short Listed');
        applicants_test.add(app5);
        
        // insert added applicants to the database
        try{
        	insert applicants_test;
        }
        
        catch(Exception e){
        	 System.debug('++++++++++++++++++++++++++++++++++++++++++++++++++++++'+e);
        }
        
      
        for(Applicant__c app:applicants_test){
        	ApplicantWrapper apwrap=new ApplicantWrapper();
        	apwrap.app=app;
        	apwrap.checked=true;
        	applicantwraps_test.add(apwrap);
        }
        
        viewapplicants_test.applicants=applicants_test;
        
        viewapplicants_test.applicant=app1;
        viewapplicants_test.wraplist=applicantwraps_test;
        
        viewapplicants_test.filterStatus();
        viewapplicants_test.wraplist=applicantwraps_test;
        viewapplicants_test.changeStatus();
        viewapplicants_test.wraplist=applicantwraps_test;
        
       
        //try{
        	viewapplicants_test.setInterViewTime();
       // }
       // catch(Exception e){
        	//System.assert(true);
       // }
        
    }
}