src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the Merchandise object</description>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_inventory__c</fullName>
        <label>Total inventory</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/StoreFront.cls
public class StoreFront {

    public String message { get; set; }

    public PageReference shop() {
        message = 'You bought: ';
        for (DisplayMerchandise p: products) {
            if (p.count > 0) {
                message += p.merchandise.name + ' (' + p.count + ') ';
            }
        }
        return null;
    }
    
    DisplayMerchandise[] products;
    
        public class DisplayMerchandise {
            public Merchandise__c merchandise { get; set; }
            
            public Decimal count { get; set; }
            
            public DisplayMerchandise(Merchandise__c item) {
                this.merchandise = item;
            }
        }
        
        public DisplayMerchandise[] getProducts() {
            if (products == null) {
                products = new DisplayMerchandise[]{};
                for (Merchandise__c item :
                    [SELECT id, name, description__c, price__c
                    FROM Merchandise__c
                    WHERE Total_Inventory__c > 0]) {
                        products.add(new DisplayMerchandise(item));
                    }
            }
            return products;
        }
}